### ISSUE TITLE
Error is throwing to Mongo DB. I am new to JS and NodeJS framework. Can you please tell me the possible solution.

### ISSUE THREAD

**Issue by abhinav-webonise** [scotch-io/node-api#8]
webonise@webonise-desktop:~/JavaScriptProjects/node-api$ node server.js
Magic happens on port 8080

/home/webonise/JavaScriptProjects/node-api/node_modules/mongodb/lib/utils.js:99
    process.nextTick(function() { throw err; });
                                  ^
MongoError: auth fails
    at Function.MongoError.create (/home/webonise/JavaScriptProjects/node-api/node_modules/mongodb-core/lib/error.js:31:11)
    at /home/webonise/JavaScriptProjects/node-api/node_modules/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/home/webonise/JavaScriptProjects/node-api/node_modules/mongodb-core/lib/connection/pool.js:429:16)
    at Connection.messageHandler (/home/webonise/JavaScriptProjects/node-api/node_modules/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/home/webonise/JavaScriptProjects/node-api/node_modules/mongodb-core/lib/connection/connection.js:309:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:548:20)
webonise@webonise-desktop:~/JavaScriptProjects/node-api$

**Comment by abhinav-webonise** [comment]
I did these changes 

mongoose.connect('mongodb://127.0.0.1:27017'); // My own database
and it workes fine.
am i on the right path ?
